version: '3.3'
services:
  mongo:
    container_name: 'mood-tracker_mongo'
    build: ./db
    volumes:
      - mood-tracker-db:/data/db
    ports:
      - 27017:27017
  api:
    container_name: 'mood-tracker_api'
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    ports:
      - 4000:8000
    links:
      - mongo

volumes:
  mood-tracker-db:
