version: '3.3'
services:
  mongo:
    container_name: 'mongo'
    build: ./db
    ports:
      - 27017:27017
  api:
    container_name: 'api'
    build: ./api
    volumes:
      - ./api:/go/src/api
    ports:
      - 8000:8000
    links:
      - mongo
  client:
    container_name: 'client'
    build: ./client
    volumes:
      - ./client/src:/client/src
    ports:
      - 3000:3000
    links:
      - api
