version: '3.8'
services:
  mongo:
    container_name: 'mongo'
    build: ./db
    ports:
      - 27017:27017
  api:
    container_name: 'api'
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    ports:
      - 4000:8000
    links:
      - mongo
